'use strict'

const knex = require('../../connection')
const BaseService = require('../BaseService')

class CustomFieldValueService extends BaseService {
    
    /**
     * Constructor
     */
    constructor() {
        super()
        //set the table name
        this.tableName = 'custom_fields_values'
    
    }

    add(customFieldValue) {
        /**
         * Inject CustomFieldHelper Service
         * * generate UUId use UUId helper
         * * then set value_id field
         */
            
        const generatedUUId = 'autogenerated'
        this.SetValueID(customFieldValue, generatedUUId)

        //add CustomFieldValue
        return super.add(customFieldValue)
    }    
    
    //Function to set value_id
    SetValueID(payload, generated_value_id) {
        payload['value_id'] = generated_value_id
    }
}

module.exports = CustomFieldValueService